### ISSUE TITLE
v1.2.0 - Error: Subscript used on non-accessible variable

### ISSUE THREAD

**Issue by itsthejb** [jlesage/docker-mkvcleaver#1]
Hi,

I no longer appear to be able to extract subtitles in the latest version (1.2.0), instead I get the following error:

![screen shot 2018-12-09 at 20 49 53](https://user-images.githubusercontent.com/557391/49702032-3aafec80-fbf4-11e8-91e7-903030d2bb37.png)

Just rolling back to v1.1.3 to see if that one is working.

**Comment by itsthejb** [comment]
Confirmed: 1.1.3 is ok, this only affects v1.2.0

**Comment by jlesage** [comment]
Hello,

It seems to be a known issue with the latest version of mkvcleaver.  See:

https://blogs.sapib.ca/apps/bugs-requests/autoit-error-4/

There is also a workaround in the bug report.  You can find the `custom.ini` file on your host under the folder you mapped to `/config`.

**Comment by itsthejb** [comment]
Ok, I'll give it a look and report back

**Comment by itsthejb** [comment]
Confirmed! Thanks for your input
