### ISSUE TITLE
REQ: add option so show hidden files

### ISSUE THREAD

**Issue by TRaSH-** [jlesage/docker-mkvcleaver#3]
Thnx for your great containerized apps

i'm actually missing one option with mkvcleaver,
show hidden files.

With mkvtoolnix you've that option

![image](https://user-images.githubusercontent.com/6155095/130348419-b7c98512-e35a-44f6-b8bb-a28f607fa40a.png)

Would be nice if you could add this also to mkvcleaver

Thnx

**Comment by jlesage** [comment]
I'm not the developper of MKVCleaver itself.  I only package the application in a Docker container.
You may try to contact the developper on his web site (https://blogs.sapib.ca/apps/mkvcleaver/), but it seems that this application is no longer developed...
