### ISSUE TITLE
parameter ENABLE_CJK_FONT=1 is not working

### ISSUE THREAD

**Issue by pbodq2** [jlesage/docker-mkvcleaver#4]
folders / filenames with those fonts mentioned cannot be displayed.
![2022-09-14 04_18_08-MKVCleaver](https://user-images.githubusercontent.com/25418300/190005361-5e42287b-d764-4134-aad8-cd193bd85e44.png)

On the contrast, I set this parameter in the docker "jlesage/mkvtoolnix" and it is successful.
![2022-09-14 04_45_31-MKVToolNix](https://user-images.githubusercontent.com/25418300/190005867-e83c5827-fd8f-47ed-8d3e-775b269505ef.png)

I compare both containers font cache content and find that they are not the same. I am not sure whether this is the reason.

![compare font cache](https://user-images.githubusercontent.com/25418300/190005310-90fd593b-b9a5-4444-8d5c-efd522331573.png)

**Comment by jlesage** [comment]
This should be fixed with the latest version of the image.

**Comment by pbodq2** [comment]
> This should be fixed with the latest version of the image.

yes, it is fixed by v23.03.1 now. Thanks
